export interface SP500Stock {
  ticker: string;
  name: string;
  sector: string;
}

export const SP500_STOCKS: SP500Stock[] = [
  // Technology
  { ticker: 'AAPL', name: 'Apple Inc', sector: 'Technology' },
  { ticker: 'MSFT', name: 'Microsoft Corp', sector: 'Technology' },
  { ticker: 'NVDA', name: 'NVIDIA Corp', sector: 'Technology' },
  { ticker: 'GOOGL', name: 'Alphabet Inc A', sector: 'Technology' },
  { ticker: 'META', name: 'Meta Platforms', sector: 'Technology' },
  { ticker: 'AVGO', name: 'Broadcom Inc', sector: 'Technology' },
  { ticker: 'ADBE', name: 'Adobe Inc', sector: 'Technology' },
  { ticker: 'CRM', name: 'Salesforce Inc', sector: 'Technology' },
  { ticker: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
  { ticker: 'INTC', name: 'Intel Corp', sector: 'Technology' },
  { ticker: 'CSCO', name: 'Cisco Systems', sector: 'Technology' },
  { ticker: 'ORCL', name: 'Oracle Corp', sector: 'Technology' },
  { ticker: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { ticker: 'IBM', name: 'IBM Corp', sector: 'Technology' },
  { ticker: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { ticker: 'QCOM', name: 'Qualcomm Inc', sector: 'Technology' },
  { ticker: 'NOW', name: 'ServiceNow Inc', sector: 'Technology' },
  { ticker: 'INTU', name: 'Intuit Inc', sector: 'Technology' },
  { ticker: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { ticker: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { ticker: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { ticker: 'MU', name: 'Micron Technology', sector: 'Technology' },
  { ticker: 'KLAC', name: 'KLA Corp', sector: 'Technology' },
  { ticker: 'SNPS', name: 'Synopsys Inc', sector: 'Technology' },
  { ticker: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
  { ticker: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { ticker: 'MCHP', name: 'Microchip Technology', sector: 'Technology' },
  { ticker: 'MSI', name: 'Motorola Solutions', sector: 'Technology' },
  { ticker: 'FTNT', name: 'Fortinet Inc', sector: 'Technology' },
  { ticker: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },

  // Healthcare
  { ticker: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { ticker: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { ticker: 'ABBV', name: 'AbbVie Inc', sector: 'Healthcare' },
  { ticker: 'MRK', name: 'Merck & Co', sector: 'Healthcare' },
  { ticker: 'PFE', name: 'Pfizer Inc', sector: 'Healthcare' },
  { ticker: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { ticker: 'ABT', name: 'Abbott Labs', sector: 'Healthcare' },
  { ticker: 'DHR', name: 'Danaher Corp', sector: 'Healthcare' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { ticker: 'AMGN', name: 'Amgen Inc', sector: 'Healthcare' },
  { ticker: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { ticker: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Healthcare' },
  { ticker: 'MDT', name: 'Medtronic plc', sector: 'Healthcare' },
  { ticker: 'SYK', name: 'Stryker Corp', sector: 'Healthcare' },
  { ticker: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
  { ticker: 'REGN', name: 'Regeneron Pharma', sector: 'Healthcare' },
  { ticker: 'ZTS', name: 'Zoetis Inc', sector: 'Healthcare' },
  { ticker: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { ticker: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { ticker: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { ticker: 'MCK', name: 'McKesson Corp', sector: 'Healthcare' },
  { ticker: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { ticker: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },

  // Financial Services
  { ticker: 'BRK-B', name: 'Berkshire Hathaway B', sector: 'Financial Services' },
  { ticker: 'JPM', name: 'JPMorgan Chase', sector: 'Financial Services' },
  { ticker: 'V', name: 'Visa Inc', sector: 'Financial Services' },
  { ticker: 'MA', name: 'Mastercard Inc', sector: 'Financial Services' },
  { ticker: 'BAC', name: 'Bank of America', sector: 'Financial Services' },
  { ticker: 'WFC', name: 'Wells Fargo', sector: 'Financial Services' },
  { ticker: 'GS', name: 'Goldman Sachs', sector: 'Financial Services' },
  { ticker: 'MS', name: 'Morgan Stanley', sector: 'Financial Services' },
  { ticker: 'SPGI', name: 'S&P Global', sector: 'Financial Services' },
  { ticker: 'BLK', name: 'BlackRock Inc', sector: 'Financial Services' },
  { ticker: 'C', name: 'Citigroup Inc', sector: 'Financial Services' },
  { ticker: 'AXP', name: 'American Express', sector: 'Financial Services' },
  { ticker: 'SCHW', name: 'Charles Schwab', sector: 'Financial Services' },
  { ticker: 'CB', name: 'Chubb Ltd', sector: 'Financial Services' },
  { ticker: 'MMC', name: 'Marsh McLennan', sector: 'Financial Services' },
  { ticker: 'PGR', name: 'Progressive Corp', sector: 'Financial Services' },
  { ticker: 'ICE', name: 'Intercontinental Exchange', sector: 'Financial Services' },
  { ticker: 'CME', name: 'CME Group', sector: 'Financial Services' },
  { ticker: 'AON', name: 'Aon plc', sector: 'Financial Services' },
  { ticker: 'USB', name: 'US Bancorp', sector: 'Financial Services' },

  // Consumer Cyclical
  { ticker: 'AMZN', name: 'Amazon.com', sector: 'Consumer Cyclical' },
  { ticker: 'TSLA', name: 'Tesla Inc', sector: 'Consumer Cyclical' },
  { ticker: 'HD', name: 'Home Depot', sector: 'Consumer Cyclical' },
  { ticker: 'MCD', name: 'McDonald\'s Corp', sector: 'Consumer Cyclical' },
  { ticker: 'NKE', name: 'Nike Inc', sector: 'Consumer Cyclical' },
  { ticker: 'LOW', name: 'Lowe\'s Cos', sector: 'Consumer Cyclical' },
  { ticker: 'SBUX', name: 'Starbucks Corp', sector: 'Consumer Cyclical' },
  { ticker: 'TJX', name: 'TJX Companies', sector: 'Consumer Cyclical' },
  { ticker: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Cyclical' },
  { ticker: 'MAR', name: 'Marriott Intl', sector: 'Consumer Cyclical' },
  { ticker: 'GM', name: 'General Motors', sector: 'Consumer Cyclical' },
  { ticker: 'F', name: 'Ford Motor', sector: 'Consumer Cyclical' },
  { ticker: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer Cyclical' },
  { ticker: 'AZO', name: 'AutoZone Inc', sector: 'Consumer Cyclical' },
  { ticker: 'ROST', name: 'Ross Stores', sector: 'Consumer Cyclical' },
  { ticker: 'DHI', name: 'DR Horton', sector: 'Consumer Cyclical' },
  { ticker: 'LEN', name: 'Lennar Corp', sector: 'Consumer Cyclical' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill', sector: 'Consumer Cyclical' },
  { ticker: 'YUM', name: 'Yum! Brands', sector: 'Consumer Cyclical' },
  { ticker: 'EBAY', name: 'eBay Inc', sector: 'Consumer Cyclical' },

  // Communication Services
  { ticker: 'GOOG', name: 'Alphabet Inc C', sector: 'Communication Services' },
  { ticker: 'NFLX', name: 'Netflix Inc', sector: 'Communication Services' },
  { ticker: 'DIS', name: 'Walt Disney', sector: 'Communication Services' },
  { ticker: 'CMCSA', name: 'Comcast Corp', sector: 'Communication Services' },
  { ticker: 'T', name: 'AT&T Inc', sector: 'Communication Services' },
  { ticker: 'VZ', name: 'Verizon Comms', sector: 'Communication Services' },
  { ticker: 'TMUS', name: 'T-Mobile US', sector: 'Communication Services' },
  { ticker: 'CHTR', name: 'Charter Comms', sector: 'Communication Services' },
  { ticker: 'EA', name: 'Electronic Arts', sector: 'Communication Services' },
  { ticker: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication Services' },
  { ticker: 'WBD', name: 'Warner Bros Discovery', sector: 'Communication Services' },
  { ticker: 'OMC', name: 'Omnicom Group', sector: 'Communication Services' },
  { ticker: 'IPG', name: 'Interpublic Group', sector: 'Communication Services' },
  { ticker: 'MTCH', name: 'Match Group', sector: 'Communication Services' },
  { ticker: 'LYV', name: 'Live Nation', sector: 'Communication Services' },

  // Industrials
  { ticker: 'CAT', name: 'Caterpillar Inc', sector: 'Industrials' },
  { ticker: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { ticker: 'RTX', name: 'RTX Corp', sector: 'Industrials' },
  { ticker: 'HON', name: 'Honeywell Intl', sector: 'Industrials' },
  { ticker: 'UPS', name: 'United Parcel Service', sector: 'Industrials' },
  { ticker: 'BA', name: 'Boeing Co', sector: 'Industrials' },
  { ticker: 'DE', name: 'Deere & Co', sector: 'Industrials' },
  { ticker: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { ticker: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { ticker: 'ADP', name: 'Automatic Data Processing', sector: 'Industrials' },
  { ticker: 'MMM', name: '3M Company', sector: 'Industrials' },
  { ticker: 'GD', name: 'General Dynamics', sector: 'Industrials' },
  { ticker: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { ticker: 'CSX', name: 'CSX Corp', sector: 'Industrials' },
  { ticker: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { ticker: 'WM', name: 'Waste Management', sector: 'Industrials' },
  { ticker: 'EMR', name: 'Emerson Electric', sector: 'Industrials' },
  { ticker: 'ITW', name: 'Illinois Tool Works', sector: 'Industrials' },
  { ticker: 'FDX', name: 'FedEx Corp', sector: 'Industrials' },
  { ticker: 'ETN', name: 'Eaton Corp', sector: 'Industrials' },

  // Consumer Defensive
  { ticker: 'PG', name: 'Procter & Gamble', sector: 'Consumer Defensive' },
  { ticker: 'KO', name: 'Coca-Cola Co', sector: 'Consumer Defensive' },
  { ticker: 'PEP', name: 'PepsiCo Inc', sector: 'Consumer Defensive' },
  { ticker: 'COST', name: 'Costco Wholesale', sector: 'Consumer Defensive' },
  { ticker: 'WMT', name: 'Walmart Inc', sector: 'Consumer Defensive' },
  { ticker: 'PM', name: 'Philip Morris Intl', sector: 'Consumer Defensive' },
  { ticker: 'MO', name: 'Altria Group', sector: 'Consumer Defensive' },
  { ticker: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Defensive' },
  { ticker: 'MDLZ', name: 'Mondelez Intl', sector: 'Consumer Defensive' },
  { ticker: 'KHC', name: 'Kraft Heinz', sector: 'Consumer Defensive' },
  { ticker: 'GIS', name: 'General Mills', sector: 'Consumer Defensive' },
  { ticker: 'STZ', name: 'Constellation Brands', sector: 'Consumer Defensive' },
  { ticker: 'SYY', name: 'Sysco Corp', sector: 'Consumer Defensive' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland', sector: 'Consumer Defensive' },
  { ticker: 'KR', name: 'Kroger Co', sector: 'Consumer Defensive' },
  { ticker: 'HSY', name: 'Hershey Co', sector: 'Consumer Defensive' },
  { ticker: 'K', name: 'Kellanova', sector: 'Consumer Defensive' },
  { ticker: 'CAG', name: 'Conagra Brands', sector: 'Consumer Defensive' },
  { ticker: 'SJM', name: 'J.M. Smucker', sector: 'Consumer Defensive' },
  { ticker: 'TGT', name: 'Target Corp', sector: 'Consumer Defensive' },

  // Energy
  { ticker: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { ticker: 'CVX', name: 'Chevron Corp', sector: 'Energy' },
  { ticker: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { ticker: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { ticker: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { ticker: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { ticker: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { ticker: 'PXD', name: 'Pioneer Natural Resources', sector: 'Energy' },
  { ticker: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { ticker: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { ticker: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { ticker: 'FANG', name: 'Diamondback Energy', sector: 'Energy' },
  { ticker: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { ticker: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },

  // Utilities
  { ticker: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { ticker: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { ticker: 'SO', name: 'Southern Co', sector: 'Utilities' },
  { ticker: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { ticker: 'AEP', name: 'American Electric Power', sector: 'Utilities' },
  { ticker: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { ticker: 'EXC', name: 'Exelon Corp', sector: 'Utilities' },
  { ticker: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { ticker: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { ticker: 'WEC', name: 'WEC Energy Group', sector: 'Utilities' },
  { ticker: 'ES', name: 'Eversource Energy', sector: 'Utilities' },
  { ticker: 'AWK', name: 'American Water Works', sector: 'Utilities' },
  { ticker: 'PCG', name: 'PG&E Corp', sector: 'Utilities' },
  { ticker: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { ticker: 'EIX', name: 'Edison Intl', sector: 'Utilities' },

  // Real Estate
  { ticker: 'PLD', name: 'Prologis Inc', sector: 'Real Estate' },
  { ticker: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { ticker: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { ticker: 'EQIX', name: 'Equinix Inc', sector: 'Real Estate' },
  { ticker: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { ticker: 'SPG', name: 'Simon Property Group', sector: 'Real Estate' },
  { ticker: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { ticker: 'WELL', name: 'Welltower Inc', sector: 'Real Estate' },
  { ticker: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { ticker: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { ticker: 'AVB', name: 'AvalonBay Communities', sector: 'Real Estate' },
  { ticker: 'EQR', name: 'Equity Residential', sector: 'Real Estate' },
  { ticker: 'ARE', name: 'Alexandria Real Estate', sector: 'Real Estate' },
  { ticker: 'MAA', name: 'Mid-America Apartment', sector: 'Real Estate' },
  { ticker: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },

  // Basic Materials
  { ticker: 'LIN', name: 'Linde plc', sector: 'Basic Materials' },
  { ticker: 'APD', name: 'Air Products', sector: 'Basic Materials' },
  { ticker: 'SHW', name: 'Sherwin-Williams', sector: 'Basic Materials' },
  { ticker: 'ECL', name: 'Ecolab Inc', sector: 'Basic Materials' },
  { ticker: 'FCX', name: 'Freeport-McMoRan', sector: 'Basic Materials' },
  { ticker: 'NUE', name: 'Nucor Corp', sector: 'Basic Materials' },
  { ticker: 'NEM', name: 'Newmont Corp', sector: 'Basic Materials' },
  { ticker: 'DOW', name: 'Dow Inc', sector: 'Basic Materials' },
  { ticker: 'DD', name: 'DuPont de Nemours', sector: 'Basic Materials' },
  { ticker: 'PPG', name: 'PPG Industries', sector: 'Basic Materials' },
  { ticker: 'VMC', name: 'Vulcan Materials', sector: 'Basic Materials' },
  { ticker: 'MLM', name: 'Martin Marietta', sector: 'Basic Materials' },
  { ticker: 'ALB', name: 'Albemarle Corp', sector: 'Basic Materials' },
  { ticker: 'CF', name: 'CF Industries', sector: 'Basic Materials' },
  { ticker: 'CTVA', name: 'Corteva Inc', sector: 'Basic Materials' },
];

export const SP500_SECTORS = Array.from(new Set(SP500_STOCKS.map(s => s.sector))).sort();
